package minebrat2.b2searchrestapidemo.entity;

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "products") //name is optional
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Product {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)//autogenerated s
	private Long id; //consdered as pkey
	private String name;
	private String description;
	private boolean isActive;
	private String sku;
	
	@CreationTimestamp //autmatically populate values
	private LocalDateTime createdDate;
    @UpdateTimestamp // //automatically populate values
	private LocalDateTime updatedDate;
	
	
	
}
