package com.minebratPractice.barebone_jpa_starter;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

@Entity
@Table(name = "EMPLOYEE_DATA") //name is optional
public class Employee {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)//autogenerated s
	private int id; //consdered as pkey
	
	@Column(name ="employee_name")
	private String name;
	
	private int age;
	
	@Column(unique = true, length = 10, nullable = true, updatable=false)
	private String ssn;
	
	@Temporal(TemporalType.TIME)
	private Date dob;
	
	@Enumerated(EnumType.STRING)
	private EmployeeType type; // mapping enum with member variable 
	
	@Transient
	private String debugString;

	@OneToOne // way to specify
	private AccessCard card;
	
	@OneToMany(mappedBy = "employee" )
	private List<PayStub> paystub ;
	
    @ManyToMany
	private List<EmailGroup> emailGroups = new ArrayList<EmailGroup>();
	
    
    public void addEmailSubscription(EmailGroup g) {
    	this.emailGroups.add(g);
    }
	public List<EmailGroup> getEmailGroups() {
		return emailGroups;
	}
	public void setEmailGroups(List<EmailGroup> emailGroups) {
		this.emailGroups = emailGroups;
	}
	public String getDebugString() {
		return debugString;
	}
	public void setDebugString(String debugString) {
		this.debugString = debugString;
	}
	public List<PayStub> getPaystub() {
		return paystub;
	}
	public void setPaystub(List<PayStub> paystub) {
		this.paystub = paystub;
	}
	public AccessCard getCard() {
		return card;
	}
	public void setCard(AccessCard card) {
		this.card = card;
	}
	public EmployeeType getType() {
		return type;
	}
	public void setType(EmployeeType type) {
		this.type = type;
	}
	public Date getDob() {
		return dob;
	}
	public void setDob(Date dob) {
		this.dob = dob;
	}
	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}
	public String getSsn() {
		return ssn;
	}
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Override
	public String toString() {
		return "Employee [id=" + id + ", name=" + name + ", age=" + age + ", ssn=" + ssn + ", dob=" + dob + ", type="
				+ type + ", debugString=" + debugString + ", card=" + card 
				+ 
//				","
//						+ " paystub=" + paystub +
						"]";
	}
	
	
	
	
}
